### ISSUE TITLE
Source will not compile

### ISSUE THREAD

**Issue by bleriotx** [Velocidex/c-aff4#143]
**Platform**: Ubuntu 16.04 and 18.04
**Release**: 3.3 RC3
**Source file**: win_pmem.cc
**Line 19**: #include resources/winpmem/resources.cc
This file does not exist. It appears to be required in order to place the device drivers in the resource section of the compiled binary. Without it - trying to build a binary will never work.

**Additional Note**: Compiling the dependencies using the instructions in README.windows is a nightmare. The libpcre++-dev build is a total mess. Copying /usr/bin/libtool does not work on either Ubuntu platform. Had to hack the configure file. Took hours to figure out.

This is painful!

**Comment by scudette** [comment]
Sadly this is the state for C++/autoconf ecosystem - building and dependency management is not so easy. The recommended way is to use docker - see README.docker

the file resources.cc is generated from scripts/encode.py and the binaries in the resources directory. You only need to generate it once since it essentially encodes the driver binaries into the .cc file

```
python3 tools/scripts/encode.py --output resources ./tools/pmem/resources/winpmem/*.{sys,exe}
```

**Comment by bleriotx** [comment]
That worked! Thanks for the quick response.
