### ISSUE TITLE
make install fails if DESTDIR is used

### ISSUE THREAD

**Issue by ryandesign** [Velocidex/c-aff4#17]
If I install with `make install DESTDIR=/somewhere`, then it fails with:

```
make[3]: Entering directory `.../c-aff4-fd984ea3cddc034740d5d03ba510a407a2e451a3/tools/pmem'
Creating deployable bundle.
rm -rf osxpmem.app osxpmem.zip
mkdir osxpmem.app/
cp README.md /opt/local/bin/osxpmem osxpmem.app/  || echo You must run make install before building a bundle.
cp: /opt/local/bin/osxpmem: No such file or directory
You must run make install before building a bundle.
dylibbundler -x osxpmem.app/osxpmem -b -d osxpmem.app/libs/ -p @executable_path/libs/ -of -od -cd
* Collecting dependencies/opt/local/libexec/llvm-5.0/bin/llvm-objdump: 'osxpmem.app/osxpmem': No such file or directory
fatal error: otool: internal objdump command failed
Cannot find file osxpmem.app/osxpmem to read its dependencies
make[3]: *** [install-exec-hook] Error 1
```

I don't have any need for a relocatable app version of osxpmem, and even if this were to succeed (because /opt/local/bin/osxpmem already existed because I already had c-aff4 installed), the resulting osxpmem.app isn't actually installed anywhere, making this code wholly pointless in `make install`. For the MacPorts aff4 port, I have removed the entire `install-exec-hook` block from tools/pmem/Makefile.am. Offer a `make bundle` target, if you like (updated to support `DESTDIR`), but it shouldn't be a required part of `make install`.

**Comment by scudette** [comment]
Yes this part of the build prepares the app package. The idea is that you deploy the app package (which is just a zip file) and not install it in your system.  Since the purpose of the app is to be an imaging app it is highly unlikely that it would be runnable on a random system because it needs ports/brew and a bunch of dependencies. It is far more useful to make a relocatable app bundle and just unzip it e.g. in /tmp/ for imaging.

Probably we dont actually want to support make install at all? 

Im happy to change the bundling option to sit behind a "make bundle". We need  it for distributing packages but probably not during development.

**Comment by scudette** [comment]
Closing due to age.
