### ISSUE TITLE
pmem with "--output -" dumps to a file named "-" rather than writing to STDOUT

### ISSUE THREAD

**Issue by justfalter** [Velocidex/c-aff4#59]
Just noticed this when I was working on testing winpmem out, some more. Where it used to be possible to dump to STDOUT with `--output -` under rc3, the current master (rc8) instead dumps memory to a file named "-". I haven't had the time to track down why this is happening, but one of the things I'm working on needs this capability.

**Comment by scudette** [comment]
Heh this bug is due to this change:
https://github.com/Velocidex/c-aff4/blob/master/tools/pmem/pmem_imager.cc#L287

The logic there is that if the output file ends with .aff4 we write an aff4 file, otherwise we write a raw output. Since "-" does not end with aff4 it just returns that as the filename. Previously this fell through to aff4_imager_utils.cc which handled this case by streaming an AFF4 on stdout.

This begs the question - which do we want to do here? When the user specifies "-" do we stream an aff4 volume over stdout, or a flat image?

Shall we require "-.aff4" to stream aff4 over stdout while "-" streams a standard stream?

**Comment by justfalter** [comment]
How about, instead of trying to detect the desired format, there was a flag that allows one to decide whether the file is aff4 format or not?

**Comment by justfalter** [comment]
It could be “—file-format flat” or “—file-format aff4”

**Comment by scudette** [comment]
Please test RC9

**Comment by justfalter** [comment]
@scudette rc9 works! Thank you!
