### ISSUE TITLE
Local file header is invalid

### ISSUE THREAD

**Issue by blschatz** [Velocidex/c-aff4#89]
At present the ZIP files produced by c-aff4 are divergent from the ZIP specification - a Data Descriptor should follow the archive content when bit 3 is set in the Local File Header. While the infozip utilities appear forgiving of violations of this subtlety of the standard, other implementations aren't (e.g. 010 editor ZIP parsers, Evimetry, and aff4-cpp-lite for a start).

THE REASON THIS IS IMPORTANT: This part of the ZIP spec allows for a ZIP implementation to start streaming content to a ZIP archive segment, without knowing what size the file with be up front. The file header uses bit 3 of the Local File Header to indicate that the size information will be supplied later, when all the content was been written into the archive. The size is then specified using the Data Descriptor.

With this current bug, if an AFF4 file is truncated, and the Central Directories are lost, it is difficult to carve out the individual files of the corrupt ZIP, as the compressed and uncompressed sizes are missing.

Some useful background info: adamhathcock/sharpcompress#88

**Comment by scudette** [comment]
You are absolutely right - we certainly intend to write bit 3 of the general flag header:

https://github.com/Velocidex/c-aff4/blob/master/aff4/zip.h#L76

Are you saying it is not written?

**Comment by blschatz** [comment]
It is written without laying down a corresponding Data Descriptor.

**Comment by blschatz** [comment]
No data descriptor ==> dont set.

**Comment by scudette** [comment]
Thanks, I must have missed writing the data descriptor on some code paths. Technically this information is not really needed as the correct data is in the central directory (and I guess this is what the other tools end up using which is why this bug did not get flagged in testing) .

But as you say, in the case where we need to recover a truncated file it is important and we should  be compliant with the standards as much as possible.
